/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.*;
import javax.swing.JButton;

/**
 *
 * @author werner.burkard
 */
public class ErstesGUI extends javax.swing.JFrame {

    int klickZaehler = 0;  // Zählt die Klicks auf unserTestButton

    /**
     * Creates new form ErstesGUI
     */
    public ErstesGUI() {
        initComponents();
        System.out.println("initComponents ist jetzt fertig.");
        KlickZaehlerListener klicky = new KlickZaehlerListener();
        BeendenListener tschuessi = new BeendenListener();

        klickButton.addActionListener(klicky);
        beendenButton.addActionListener(tschuessi);
        System.out.println("Ich, das ErstesGUI-Objekt habe gerade dem klickButton gesagt, dass klicky sein Listener ist.");
        System.out.println("Ich, das ErstesGUI-Objekt habe gerade dem beendenButton gesagt, dass tschuessi sein Listener ist.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klickButton = new javax.swing.JButton();
        beendenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        klickButton.setText("Ich wurde 0 mal geklickt");

        beendenButton.setBackground(new java.awt.Color(255, 51, 51));
        beendenButton.setText("beenden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(klickButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beendenButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(klickButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(beendenButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class KlickZaehlerListener implements ActionListener{

        public KlickZaehlerListener() {
            System.out.println("Bä Bäh, ich bins,das neue Baby KlickzaehlerListener");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("Hi Leute, ich bins, klein Klicky");
            System.out.println("Eben kam gerade ein Event rein!!");
            System.out.println("Daher ändere ich den KlickButton!");
            klickZaehler++;
            JButton unserWerfer = (JButton) e.getSource(); // Welcher Button hat den Event geworfen?
            String neuerText = "Ich wurde "+klickZaehler + " mal geklickt";
            unserWerfer.setText(neuerText);
           }       
    }

    class BeendenListener implements ActionListener {

        public BeendenListener() {

            System.out.println("Bä Bäh, ich bins,das neue Baby BeendenListener");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("Hi Leute, ich bins, klein Tschüssi");
            System.out.println("Eben kam gerade ein Event rein!!");
            System.out.println("Daher mache ich die APP jetzt dicht!");
            System.exit(0);  // Programm beenden
        }
    }  // Ende der inneren Klasse BeendenListener

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErstesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErstesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErstesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErstesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ErstesGUI babygui;
                //babygui = new ErstesGUI();
                //babygui.setVisible(true);
                new ErstesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beendenButton;
    private javax.swing.JButton klickButton;
    // End of variables declaration//GEN-END:variables
}
