/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial_ui;

/**
 *
 * @author Jonathan Hinkel
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        mySecondPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        myFirstButton = new javax.swing.JButton();
        mySecondPanel = new javax.swing.JPanel();
        buttonPanel2 = new javax.swing.JButton();
        myFirstPanel = new javax.swing.JPanel();
        panelButton = new javax.swing.JButton();
        textFieldPanel1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenuButton = new javax.swing.JMenu();
        closeButton = new javax.swing.JRadioButtonMenuItem();
        openDialog = new javax.swing.JMenuItem();
        editMenuButton = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myFirstButton.setText("Test");
        myFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myFirstButtonActionPerformed(evt);
            }
        });

        buttonPanel2.setText("Hide");
        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mySecondPanelLayout = new javax.swing.GroupLayout(mySecondPanel);
        mySecondPanel.setLayout(mySecondPanelLayout);
        mySecondPanelLayout.setHorizontalGroup(
            mySecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mySecondPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        mySecondPanelLayout.setVerticalGroup(
            mySecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mySecondPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(buttonPanel2)
                .addContainerGap())
        );

        panelButton.setText("Hide this panel");
        panelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelButtonActionPerformed(evt);
            }
        });

        textFieldPanel1.setText("THis is the first panel.");

        javax.swing.GroupLayout myFirstPanelLayout = new javax.swing.GroupLayout(myFirstPanel);
        myFirstPanel.setLayout(myFirstPanelLayout);
        myFirstPanelLayout.setHorizontalGroup(
            myFirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFirstPanelLayout.createSequentialGroup()
                .addGroup(myFirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myFirstPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(textFieldPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myFirstPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        myFirstPanelLayout.setVerticalGroup(
            myFirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFirstPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textFieldPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        fileMenuButton.setText("File");

        closeButton.setSelected(true);
        closeButton.setText("Exit");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        fileMenuButton.add(closeButton);

        openDialog.setText("Dialog");
        openDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDialogActionPerformed(evt);
            }
        });
        fileMenuButton.add(openDialog);

        jMenuBar1.add(fileMenuButton);

        editMenuButton.setText("Edit");
        jMenuBar1.add(editMenuButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(myFirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myFirstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(mySecondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(myFirstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(myFirstButton))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(mySecondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(135, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFirstButtonActionPerformed
        System.out.println("The button was pressed.");
        switchPanels();
    }//GEN-LAST:event_myFirstButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void openDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDialogActionPerformed
        MyDialog dialog = new MyDialog(this, true);
        dialog.setVisible(true); 
    }//GEN-LAST:event_openDialogActionPerformed

    private void panelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelButtonActionPerformed
        myFirstPanel.setVisible(false);
    }//GEN-LAST:event_panelButtonActionPerformed

    private void buttonPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel2ActionPerformed
        mySecondPanel.setVisible(false); 
    }//GEN-LAST:event_buttonPanel2ActionPerformed

    private void switchPanels() {
        myFirstPanel.setVisible(!myFirstPanel.isVisible()); 
        mySecondPanel.setVisible(!mySecondPanel.isVisible()); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPanel2;
    private javax.swing.JRadioButtonMenuItem closeButton;
    private javax.swing.JMenu editMenuButton;
    private javax.swing.JMenu fileMenuButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton myFirstButton;
    private javax.swing.JPanel myFirstPanel;
    private javax.swing.JPanel mySecondPanel;
    private javax.swing.JMenuItem openDialog;
    private javax.swing.JButton panelButton;
    private javax.swing.JTextField textFieldPanel1;
    // End of variables declaration//GEN-END:variables
}
